[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = .8
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = .2
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .6
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .6
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = .5
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = .5
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .5
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = .8
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = .2
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .6
start-sleep -seconds 3
[audio]::Volume = .1
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .2
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = .5
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .2
start-sleep -seconds 3
[audio]::Volume = .6
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = .8
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = .2
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .6
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .6
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = .5
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = .5
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .5
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = .8
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = .2
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .6
start-sleep -seconds 3
[audio]::Volume = .1
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .2
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = .5
start-sleep -seconds 3
[audio]::Volume = .4
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .2
start-sleep -seconds 3
[audio]::Volume = .6
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
[audio]::Volume = .3
start-sleep -seconds 3
[audio]::Volume = 1
start-sleep -seconds 3
