msiexec /qn /i AtHoc268.msi /l*vx AtHoc268.log BASEURL=https://alerts.aetc.af.mil/config/baseurl.asp PID=2039424 RUNAFTERINSTALL=N DESKBAR=N TOOLBAR=N SILENT=Y VALIDATECERT=Y MANDATESSL=Y UNINSTALLOPTION=Y 


